version: '3.5'

services:
  todolist-account:
    image: mysql:8.1
    container_name: todolist-account
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: todolist-account
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
